### PR TITLE
fixes bug #270

### PR DESCRIPTION
**Pull request by johannesgerer**
#270

### CODE REVIEW

**Comment by yalishizhude** [comment]
Please merge thi PR quickly...

**Comment by johannesgerer** [comment]
There is no merging activity since Jun 2016

**Comment by jgnewman** [comment]
Duplicate of [this pr](https://github.com/xorcery/retinajs/pull/256) which I'm hoping can be merged soon.

@xorcery you can close this one after merging the other.

**Comment by jgnewman** [comment]
Closed because we merged a duplicate PR from earlier

**Pull request closed without merging**
